name: FlashBot
description: This is the FlashBot app.

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: 0.5.0
  redux: 3.0.0
  flutter_markdown: 0.1.5
  url_launcher: 3.0.0
  intl: 0.15.6
  http: "^0.11.3+16"

flutter:
  uses-material-design: true
  fonts:
    - family: ibm-sans
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
        - asset: fonts/IBMPlexSans-Italic.ttf
          style: italic
        - asset: fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.ttf
          style: italic
          weight: 500