name: lakes
description: Demonstrates building a layout for the "Lakes" app.

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: 0.5.0
  redux: 3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ibm-sans
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
        - asset: fonts/IBMPlexSans-Italic.ttf
          style: italic
        - asset: fonts/IBMPlexSans-Bold.ttf
          weight: 500
        - asset: fonts/IBMPlexSans-BoldItalic.ttf
          style: italic
          weight: 500
    - family: ibm-serif
      fonts:
        - asset: fonts/IBMPlexSerif-SemiBold.ttf