name: lakes
description: Demonstrates building a layout for the "Lakes" app.

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: 0.5.0
  redux: 3.0.0

flutter:
  uses-material-design: true
    